apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart: metallb
  repo: https://metallb.github.io/metallb
  version: "@VERSION@"
